# Generated by Django 3.0.8 on 2020-07-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
    ]
