# Generated by Django 3.0.8 on 2020-07-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200715_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Date_of_Birth',
            field=models.DateField(null=True),
        ),
    ]
