# Generated by Django 3.0.6 on 2020-06-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200605_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
